version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGODB_USER: dev
      MONGODB_PASSWORD: password
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - "mongodb-data:/data/db"

  tracking-server:
    image: node
    container_name: tracking-server
    working_dir: /usr/src/app
    environment:
      NODE_PATH: /usr/src/app
      DB_NAME: tracking
      DB_URL: mongodb://mongodb/
      MAIL_HOST: smtp.gmail.com
      MAIL_USER: tottori.tracking@gmail.com
      MAIL_PASS: tracking
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: tracking
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: password

    links:
      - mongodb:mongo
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    command: ["sh", "-c", "npm install && npm run dev"]

  tracking-frontend:
    image: node
    container_name: tracking-frontend
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - tracking-server
    volumes:
      - ./webapp:/usr/src/app/
      - /usr/src/app/node_modules
    command: ["sh", "-c", "npm install && npm run start:docker"]

volumes:
  mongodb-data:
    external: true
